project:
  type: website

website:
  title: "The Data Center Ecosystem"
  navbar:
    left:
      - href: index.html
        text: Home
      - href: Why.html
        text: Why It Matters
      - href: Getting-Started.html
        text: Getting Started
      - text: Pages
        menu:
          - text: Facility Providers
            href: Facilities.html
          - text: Power & Cooling
            href: powerHVAC.html
          - text: Networking
            href: Networking.html
          - text: Hardware
            href: Hardware.html
          - text: Cloud Services
            href: Cloud.html
          - text: Security
            href: Security.html
          - text: Monitoring & Automation
            href: Monitoring.html
          - text: Engineering & Construction
            href: Engineering.html
          - text: Recycling & Lifecycle
            href: Recycling.html

  page-footer:
    center: "© 2025 Data Center Ecosystem Guide"
  repo-url: https://github.com/yourusername/yourrepo
  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
